/** Design tokens aligned with ATHLO mockups (blue on black). */
export const theme = {
  colors: {
    background: '#000000',
    surface: '#1C1C1E',
    surfaceLight: '#2C2C2E',
    surfaceElevated: '#3A3A3C',
    primary: '#007AFF',
    primaryDark: '#0056CC',
    primaryLight: '#4DA3FF',
    text: '#FFFFFF',
    textMuted: '#8E8E93',
    textSecondary: '#AEAEB2',
    border: '#2C2C2E',
    error: '#FF3B30',
    warning: '#FF9500',
    success: '#34C759',
    orange: '#FF9500',
    green: '#34C759',
    purple: '#AF52DE',
    yellow: '#FFCC00',
    red: '#FF3B30',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 999,
  },
  typography: {
    hero: { fontSize: 32, fontWeight: '700' as const, lineHeight: 40 },
    title: { fontSize: 24, fontWeight: '700' as const, lineHeight: 32 },
    subtitle: { fontSize: 16, fontWeight: '600' as const, lineHeight: 22 },
    body: { fontSize: 16, fontWeight: '400' as const, lineHeight: 22 },
    caption: { fontSize: 13, fontWeight: '400' as const, lineHeight: 18 },
    label: { fontSize: 14, fontWeight: '500' as const, lineHeight: 18 },
    tagline: { fontSize: 11, fontWeight: '500' as const, letterSpacing: 2 },
  },
} as const;
